# Generated by Django 5.2.17 on 2026-09-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザー識別子')),
                ('role', models.CharField(choices=[('user', 'ユーザー'), ('bot', 'ボット')], max_length=10, verbose_name='発言者')),
                ('content', models.TextField(verbose_name='メッセージ内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '会話履歴',
                'verbose_name_plural': '会話履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
