# Generated by Django 5.2.17 on 2026-09-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='needs_human',
            field=models.BooleanField(default=False, verbose_name='要引き継ぎ'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', '未対応'), ('handoff', '要引き継ぎ'), ('resolved', '解決済み')], default='open', max_length=10, verbose_name='対応状況'),
        ),
    ]
