# Generated by Django 5.2.17 on 2026-09-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザー識別子')),
                ('kind', models.CharField(choices=[('reservation', '予約'), ('repair', '修理受付')], default='reservation', max_length=20, verbose_name='種別')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='お名前')),
                ('preferred_datetime', models.CharField(blank=True, max_length=255, verbose_name='希望日時')),
                ('detail', models.TextField(blank=True, verbose_name='内容')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('status', models.CharField(choices=[('pending', '受付中'), ('confirmed', '確定待ち'), ('done', '確定済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '予約・修理受付',
                'verbose_name_plural': '予約・修理受付',
                'ordering': ['-created_at'],
            },
        ),
    ]
