# Generated by Django 5.2.17 on 2026-09-08 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='step',
            field=models.CharField(blank=True, max_length=20, verbose_name='入力中ステップ'),
        ),
    ]
