# Generated by Django 5.2.17 on 2026-09-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True, verbose_name='ユーザー識別子')),
                ('count', models.IntegerField(default=0, verbose_name='カウント')),
                ('window_start', models.DateTimeField(auto_now_add=True, verbose_name='ウィンドウ開始日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'レート制限',
                'verbose_name_plural': 'レート制限',
            },
        ),
    ]
