# Generated by Django 5.2.17 on 2026-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店舗名')),
                ('business_hours', models.CharField(blank=True, max_length=255, verbose_name='営業時間')),
                ('closed_days', models.CharField(blank=True, max_length=255, verbose_name='定休日')),
                ('access', models.TextField(blank=True, verbose_name='アクセス情報')),
                ('payment_methods', models.TextField(blank=True, verbose_name='支払い方法')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='住所')),
            ],
            options={
                'verbose_name': '店舗',
                'verbose_name_plural': '店舗',
            },
        ),
    ]
